# Required to run your project under the correct environment.

language: php

# Versions of PHP you want your project run with.

php:
 - 7.3

# Commands to be run before your environment runs.

before_script:

 - composer self-update
 - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.

# allow_failures: Allow this build to fail under the specified environments.

# fast_finish: If your build fails do not continue trying to build, just stop.

matrix:

 fast_finish: true

# Customize when the notification emails are sent.

notifications:
  on_success: never
  on_failure: always

# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
 directories:
   - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
 # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
 fast_finish: true
 include:
   - php: 7.3

# Define an environment variable
env:
 - SYMFONY_VERSION="5.1.*" DB=mysql
 

# Update composer
before-install:
 - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
 - composer install

script:
  - phpunit --version

deploy:
  provider: releases
  token: ${{GITHUB_TOKEN}}
  edge: true # opt in to dpl v2
  on:
    tags: true

# After a build, send email notification with the build results
notifications:
 email: imperium.emperor@gmail.com